const express = require('express');
const healthRoutes = require('./healthRoute');
const authRoute = require('./authRoute');
const customerRoute = require('./customerRoute');
const caseRoute = require('./caseRoute');
const appointmentRoute = require('./appointmentRoute');
const sessionRoute = require('./sessionRoute');
const elaycoinRoute = require('./elaycoinRoute');
const configRoute = require('./configRoute');
const studioRoute = require('./studioRoute');
const studiosRoute = require('./studiosRoute');
const fileRoute = require('./fileRoute');
const shopRoute = require('./shopRoute');
const studioTransferRoute = require('./studioTransferRoute');
const nachsorgeRoute = require('./nachsorgeRoute');
const verblassungRoute = require('./verblassungRoute');
const chatRoute = require('./chatRoute');
const messagingRoute = require('./messagingRoute');
const pushTokenRoute = require('./pushTokenRoute');
const notificationRoute = require('./notificationRoute');

const router = express.Router();

router.use(healthRoutes);
router.use('/auth', authRoute);
router.use('/customers', customerRoute);
router.use('/cases', caseRoute);
router.use('/appointments', appointmentRoute);
router.use('/sessions', sessionRoute);
router.use('/elaycoins', elaycoinRoute);
router.use('/config', configRoute);
router.use('/studio', studioRoute);
router.use('/studios', studiosRoute);
router.use('/files', fileRoute);
router.use('/shop', shopRoute);
router.use('/admin/shop', require('./adminShopRoute'));
router.use('/studio-transfers', studioTransferRoute);
router.use('/nachsorge', nachsorgeRoute);
router.use('/verblassung', verblassungRoute);
router.use('/chat', chatRoute);
router.use('/messaging', messagingRoute);
router.use('/push-tokens', pushTokenRoute);
router.use('/notifications', notificationRoute);

module.exports = router;
