const ELAYCOIN_COIN_GELDWERT = 100;
const ELAYCOIN_CHF_PRO_EINHEIT = 5;
const ELAYCOIN_TAGESLIMIT = 800;
const ELAYCOIN_MIN = 0;
const ELAYCOIN_MAX = 1000;
const COIN_VERFALL_MONATE = 12;
const ELAYCOIN_VERFALL_RESET_TRIGGER = [
    'Sitzung',
    'Nachsorge-Check',
    'Termin',
    'Einkauf',
];

const ELAYCOIN_SITUATIONS = [
    {
        key: 'termin_wahrgenommen',
        label: 'Termin wahrgenommen',
        label_en: 'Appointment attended',
        kat: 'BEHANDLUNGSTREUE',
        coins: 100,
        aktiv: true,
        einmalig: false,
    },
    {
        key: 'sitzung_meilenstein_3',
        label: 'Meilenstein: 3. Sitzung',
        label_en: 'Milestone: 3rd session',
        kat: 'BEHANDLUNGSTREUE',
        coins: 150,
        aktiv: true,
        einmalig: true,
    },
    {
        key: 'sitzung_meilenstein_5',
        label: 'Meilenstein: 5. Sitzung',
        label_en: 'Milestone: 5th session',
        kat: 'BEHANDLUNGSTREUE',
        coins: 250,
        aktiv: true,
        einmalig: true,
    },
    {
        key: 'sitzung_meilenstein_10',
        label: 'Meilenstein: 10. Sitzung',
        label_en: 'Milestone: 10th session',
        kat: 'BEHANDLUNGSTREUE',
        coins: 500,
        aktiv: true,
        einmalig: true,
    },
    {
        key: 'behandlung_abgeschlossen',
        label: 'Behandlung abgeschlossen',
        label_en: 'Treatment completed',
        kat: 'BEHANDLUNGSTREUE',
        coins: 500,
        aktiv: true,
        einmalig: true,
    },
    {
        key: 'fruehbucher',
        label: 'Frühbucher-Bonus',
        label_en: 'Early-booking bonus',
        kat: 'BEHANDLUNGSTREUE',
        coins: 50,
        aktiv: true,
        einmalig: false,
    },
    {
        key: 'heilungsfoto_hochgeladen',
        label: 'Heilungsfoto hochgeladen',
        label_en: 'Healing photo uploaded',
        kat: 'NACHSORGE',
        coins: 80,
        aktiv: true,
        einmalig: false,
        limitProSitzung: 1,
    },
    {
        key: 'nachsorge_check',
        label: 'Nachsorge-Check eingereicht',
        label_en: 'Aftercare check submitted',
        kat: 'NACHSORGE',
        coins: 50,
        aktiv: true,
        einmalig: false,
        limitTage: 7,
    },
    {
        key: 'nachsorge_serie',
        label: 'Nachsorge-Serie (3 Checks)',
        label_en: 'Aftercare series (3 checks)',
        kat: 'NACHSORGE',
        coins: 120,
        aktiv: true,
        einmalig: false,
    },
    {
        key: 'ki_training_freigabe',
        label: 'KI-Training freigegeben',
        label_en: 'AI training approved',
        kat: 'NACHSORGE',
        coins: 100,
        aktiv: true,
        einmalig: true,
    },
    {
        key: 'anamnese_vollstaendig',
        label: 'Anamnese vollständig',
        label_en: 'Anamnesis completed',
        kat: 'GESUNDHEIT',
        coins: 100,
        aktiv: true,
        einmalig: true,
    },
    {
        key: 'lifestyle_update',
        label: 'Lifestyle-Update',
        label_en: 'Lifestyle update',
        kat: 'GESUNDHEIT',
        coins: 30,
        aktiv: true,
        einmalig: false,
        limitTage: 30,
    },
    {
        key: 'erster_einkauf',
        label: 'Erster Einkauf',
        label_en: 'First purchase',
        kat: 'SHOP',
        coins: 150,
        aktiv: true,
        einmalig: true,
    },
    {
        key: 'nachsorge_produkt_gekauft',
        label: 'Nachsorge-Produkt gekauft',
        label_en: 'Aftercare product purchased',
        kat: 'SHOP',
        coins: 40,
        aktiv: true,
        einmalig: false,
    },
    {
        key: 'shop_einloesung',
        label: 'Elaycoins im Shop eingelöst',
        label_en: 'Elaycoins redeemed in shop',
        kat: 'SHOP',
        coins: 0,
        aktiv: true,
        istMalus: true,
    },
    {
        key: 'admin_korrektur',
        label: 'Admin-Korrektur',
        label_en: 'Admin correction',
        kat: 'ADMIN',
        coins: 0,
        aktiv: true,
        einmalig: false,
    },
    {
        key: 'freund_geworben',
        label: 'Freund geworben',
        label_en: 'Friend referred',
        kat: 'WACHSTUM',
        coins: 500,
        aktiv: true,
        einmalig: false,
    },
    {
        key: 'bewertung_geschrieben',
        label: 'Bewertung geschrieben',
        label_en: 'Review written',
        kat: 'WACHSTUM',
        coins: 200,
        aktiv: true,
        einmalig: true,
    },
    {
        key: 'story_geteilt',
        label: 'Story geteilt',
        label_en: 'Story shared',
        kat: 'WACHSTUM',
        coins: 150,
        aktiv: true,
        einmalig: true,
    },
    {
        key: 'profil_vervollstaendigt',
        label: 'Profil vervollständigt',
        label_en: 'Profile completed',
        kat: 'ENGAGEMENT',
        coins: 50,
        aktiv: true,
        einmalig: true,
    },
    {
        key: 'erster_elaya_chat',
        label: 'Erster Elaya-Chat',
        label_en: 'First Elaya chat',
        kat: 'ENGAGEMENT',
        coins: 30,
        aktiv: true,
        einmalig: true,
    },
    {
        key: 'jubilaeum_1_jahr',
        label: '1-Jahres-Jubiläum',
        label_en: '1-year anniversary',
        kat: 'ENGAGEMENT',
        coins: 200,
        aktiv: true,
        einmalig: false,
        limitTage: 365,
    },
    {
        key: 'no_show',
        label: 'Nicht erschienen',
        label_en: 'No-show',
        kat: 'ABZÜGE',
        coins: 150,
        aktiv: true,
        istMalus: true,
    },
    {
        key: 'kurzfristige_stornierung',
        label: 'Nicht rechtzeitig storniert (< 24h)',
        label_en: 'Cancelled too late (< 24h)',
        kat: 'ABZÜGE',
        coins: 80,
        aktiv: true,
        istMalus: true,
    },
];

const ELAYCOIN_SITUATION_MAP = Object.fromEntries(ELAYCOIN_SITUATIONS.map((s) => [s.key, s]));

/** Prototype Elaycoin-Regeln defaults — platform-editable override of engine constants. */
const DEFAULT_ELAYCOIN_REGELN = {
    geldwert_coins: ELAYCOIN_COIN_GELDWERT,
    geldwert_chf: ELAYCOIN_CHF_PRO_EINHEIT,
    tageslimit_pro_kunde: ELAYCOIN_TAGESLIMIT,
    grenze_pro_aktion_min: ELAYCOIN_MIN,
    grenze_pro_aktion_max: ELAYCOIN_MAX,
    verfall_reset_trigger: [...ELAYCOIN_VERFALL_RESET_TRIGGER],
    situations: ELAYCOIN_SITUATIONS.map((s) => ({ ...s })),
};

module.exports = {
    ELAYCOIN_COIN_GELDWERT,
    ELAYCOIN_CHF_PRO_EINHEIT,
    ELAYCOIN_TAGESLIMIT,
    ELAYCOIN_MIN,
    ELAYCOIN_MAX,
    COIN_VERFALL_MONATE,
    ELAYCOIN_VERFALL_RESET_TRIGGER,
    ELAYCOIN_SITUATIONS,
    ELAYCOIN_SITUATION_MAP,
    DEFAULT_ELAYCOIN_REGELN,
};
