const EXCEL_PLAUSIBILITY_EXAMPLES = [
    {
        id: 'example_1',
        title: 'Small black tattoo',
        input: {
            tc_size_length: 3,
            tc_size_width: 2,
            tc_colors_present: ['black'],
            tc_depth: 'normal',
            tc_age_years: 8,
            skin_fitzpatrick_type: 'II',
            tc_body_location_main: 'arm',
            tc_coverup: 'none',
            goal_target: 'full_removal',
            tc_density: 'medium',
            tc_saturation: 'medium',
        },
        expected: {
            area: 6,
            raw_price: 18,
            price_per_session: 90,
            sessions_min: 6,
            sessions_max: 8,
            total_min: 540,
            total_max: 720,
        },
    },
    {
        id: 'example_2',
        title: 'Medium colorful tattoo',
        input: {
            tc_size_length: 8,
            tc_size_width: 5,
            tc_colors_present: ['red', 'blue', 'green', 'orange'],
            tc_depth: 'deep',
            tc_age_years: 3,
            skin_fitzpatrick_type: 'III',
            tc_body_location_main: 'arm',
            tc_coverup: 'none',
            goal_target: 'full_removal',
            tc_type: 'professional',
            tc_density: 'medium',
            tc_saturation: 'medium',
        },
        expected: {
            area: 40,
            raw_price: 120,
            price_per_session: 120,
            sessions_min: 11,
            sessions_max: 13,
            total_min: 1320,
            total_max: 1560,
        },
    },
    {
        id: 'example_3',
        title: 'Large cover-up on hand',
        input: {
            tc_size_length: 10,
            tc_size_width: 8,
            tc_colors_present: ['black', 'red'],
            tc_age_years: 2,
            skin_fitzpatrick_type: 'IV',
            tc_body_location_main: 'hand',
            tc_coverup: 'multiple',
            goal_target: 'full_removal',
            tc_type: 'professional',
            tc_density: 'medium',
            tc_saturation: 'medium',
        },
        expected: {
            area: 80,
            raw_price: 240,
            price_per_session: 240,
            sessions_min: 13,
            sessions_max: 15,
            total_min: 3120,
            total_max: 3600,
        },
    },
];

module.exports = {
    EXCEL_PLAUSIBILITY_EXAMPLES,
};
